# Generated by Django 2.1.3 on 2018-11-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perris',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='perris',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perris',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='perris',
            name='state',
        ),
        migrations.AddField(
            model_name='perris',
            name='color',
            field=models.CharField(default='black', max_length=255),
        ),
        migrations.AddField(
            model_name='perris',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
