# Generated by Django 2.1.3 on 2018-11-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris3', '0003_auto_20181126_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perris',
            name='imageUrl',
        ),
    ]
