# Generated by Django 2.1.3 on 2018-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.TextField(default='')),
                ('state', models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado'), ('Rescatado', 'Rescatado')], default='Rescatado', max_length=10)),
                ('imageUrl', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
