# Generated by Django 2.1.3 on 2018-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris3', '0002_auto_20181126_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perris',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perris',
            name='color',
        ),
        migrations.RemoveField(
            model_name='perris',
            name='name',
        ),
        migrations.AddField(
            model_name='perris',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perris',
            name='raza',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perris',
            name='state',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado'), ('Rescatado', 'Rescatado')], default='Rescatado', max_length=10),
        ),
    ]
