# Generated by Django 2.1.3 on 2018-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris3', '0004_remove_perris_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='perris',
            name='imageUrl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
